# Generated by Django 6.0 on 2026-01-12 09:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_sub', models.CharField(db_index=True, max_length=255)),
                ('action', models.CharField(max_length=64)),
                ('key', models.CharField(blank=True, max_length=2048, null=True)),
                ('success', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StorageShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_sub', models.CharField(db_index=True, max_length=255)),
                ('target_sub', models.CharField(db_index=True, max_length=255)),
                ('key', models.CharField(max_length=1024)),
                ('is_directory', models.BooleanField(default=False)),
                ('permission', models.CharField(default='read', max_length=16)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_sub', models.CharField(db_index=True, max_length=255)),
                ('key', models.CharField(db_index=True, max_length=1024)),
                ('version', models.PositiveIntegerField()),
                ('object_key', models.CharField(max_length=2048)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('etag', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-version'],
                'unique_together': {('owner_sub', 'key', 'version')},
            },
        ),
    ]
